#!/usr/bin/env python3
"""
Email Reporter Module
Generates JSON, CSV, and HTML reports from email monitoring and verification data.
"""

import csv
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family: Arial, sans-serif; background: #f4f4f9; color: #333; margin: 0; padding: 20px; }}
  h1 {{ color: #2c3e50; }}
  h2 {{ color: #34495e; border-bottom: 2px solid #3498db; padding-bottom: 5px; }}
  table {{ width: 100%; border-collapse: collapse; margin-bottom: 30px; background: #fff; }}
  th {{ background: #3498db; color: #fff; padding: 10px; text-align: left; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #ddd; word-break: break-word; }}
  tr:nth-child(even) {{ background: #f2f2f2; }}
  .badge {{ display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 0.85em; }}
  .badge-green {{ background: #27ae60; color: #fff; }}
  .badge-red {{ background: #e74c3c; color: #fff; }}
  .badge-yellow {{ background: #f39c12; color: #fff; }}
  .badge-blue {{ background: #2980b9; color: #fff; }}
  .badge-grey {{ background: #7f8c8d; color: #fff; }}
  .summary {{ background: #eaf4fb; border-left: 4px solid #3498db; padding: 15px; margin-bottom: 20px; }}
  .footer {{ margin-top: 40px; font-size: 0.8em; color: #999; }}
  pre {{ background: #2d2d2d; color: #f8f8f2; padding: 15px; overflow: auto; border-radius: 5px; font-size: 0.85em; }}
</style>
</head>
<body>
<h1>📧 {title}</h1>
<p>Generated: {generated_at}</p>
{body}
<div class="footer">Generated by Twt_seeds Email Monitor Tool</div>
</body>
</html>
"""


class EmailReporter:
    """
    Generates formatted reports from email monitoring and verification data.
    Supports JSON, CSV, and HTML output formats.
    """

    def __init__(self, output_dir: str = "output"):
        """
        Initialize the reporter.

        Args:
            output_dir: Directory for saving reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Email Inbox Reports
    # ------------------------------------------------------------------

    def report_emails_json(self, emails: List[Dict], filepath: str = None) -> str:
        """
        Export email list to JSON report.

        Args:
            emails: List of email data dicts
            filepath: Output path (auto-generated if None)

        Returns:
            Absolute path to report file
        """
        filepath = filepath or str(self.output_dir / f"emails_{self._ts()}.json")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(emails, f, indent=2, ensure_ascii=False, default=str)
        return os.path.abspath(filepath)

    def report_emails_csv(self, emails: List[Dict], filepath: str = None) -> str:
        """
        Export email list to CSV report.

        Args:
            emails: List of email data dicts
            filepath: Output path (auto-generated if None)

        Returns:
            Absolute path to report file
        """
        filepath = filepath or str(self.output_dir / f"emails_{self._ts()}.csv")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)

        flat_emails = [self._flatten(em) for em in emails]
        if not flat_emails:
            return os.path.abspath(filepath)

        fieldnames = list(flat_emails[0].keys())
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction='ignore')
            writer.writeheader()
            writer.writerows(flat_emails)
        return os.path.abspath(filepath)

    def report_emails_html(self, emails: List[Dict], filepath: str = None, account: str = "") -> str:
        """
        Generate HTML report for fetched emails.

        Args:
            emails: List of email data dicts
            filepath: Output path (auto-generated if None)
            account: Account label for the report title

        Returns:
            Absolute path to HTML report
        """
        filepath = filepath or str(self.output_dir / f"emails_{self._ts()}.html")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)

        title = f"Email Inbox Report — {account}" if account else "Email Inbox Report"
        rows = []
        for em in emails:
            unread_badge = '<span class="badge badge-blue">Unread</span>' if em.get('is_unread') else ''
            attach_badge = '<span class="badge badge-yellow">📎</span>' if em.get('has_attachments') else ''
            rows.append(
                f"<tr>"
                f"<td>{self._esc(em.get('date', ''))}</td>"
                f"<td>{self._esc(em.get('from', ''))}</td>"
                f"<td>{self._esc(em.get('subject', ''))}</td>"
                f"<td>{self._esc(em.get('preview', ''))}</td>"
                f"<td>{unread_badge}{attach_badge}</td>"
                f"</tr>"
            )

        body = f"""
<div class="summary">
  <strong>Total emails:</strong> {len(emails)}&nbsp;&nbsp;
  <strong>Unread:</strong> {sum(1 for e in emails if e.get('is_unread'))}
</div>
<h2>Emails</h2>
<table>
  <thead><tr><th>Date</th><th>From</th><th>Subject</th><th>Preview</th><th>Flags</th></tr></thead>
  <tbody>{''.join(rows)}</tbody>
</table>
"""
        html = _HTML_TEMPLATE.format(
            title=title,
            generated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            body=body,
        )
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        return os.path.abspath(filepath)

    # ------------------------------------------------------------------
    # Verification Reports
    # ------------------------------------------------------------------

    def report_verification_json(self, results: List[Dict], filepath: str = None) -> str:
        """Export verification results to JSON."""
        filepath = filepath or str(self.output_dir / f"verifications_{self._ts()}.json")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False, default=str)
        return os.path.abspath(filepath)

    def report_verification_html(self, results: List[Dict], filepath: str = None) -> str:
        """
        Generate HTML report for email verifications.

        Args:
            results: List of verification result dicts
            filepath: Output path (auto-generated if None)

        Returns:
            Absolute path to HTML report
        """
        filepath = filepath or str(self.output_dir / f"verifications_{self._ts()}.html")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for r in results:
            conf = r.get('confidence', 'unknown')
            risk = r.get('risk_level', 'unknown')
            conf_badge = self._confidence_badge(conf)
            risk_badge = self._risk_badge(risk)
            format_ok = '<span class="badge badge-green">✓</span>' if r.get('format_valid') else '<span class="badge badge-red">✗</span>'
            mx_ok = '<span class="badge badge-green">✓</span>' if r.get('mx_found') else '<span class="badge badge-red">✗</span>'
            smtp_ok = self._smtp_badge(r.get('smtp_valid'))
            disposable = '<span class="badge badge-red">Yes</span>' if r.get('is_disposable') else '<span class="badge badge-green">No</span>'
            rows.append(
                f"<tr>"
                f"<td>{self._esc(r.get('email', ''))}</td>"
                f"<td>{format_ok}</td>"
                f"<td>{mx_ok}</td>"
                f"<td>{smtp_ok}</td>"
                f"<td>{disposable}</td>"
                f"<td>{conf_badge}</td>"
                f"<td>{risk_badge}</td>"
                f"</tr>"
            )

        deliverable = sum(1 for r in results if r.get('is_deliverable'))
        body = f"""
<div class="summary">
  <strong>Total verified:</strong> {len(results)}&nbsp;&nbsp;
  <strong>Deliverable:</strong> {deliverable}&nbsp;&nbsp;
  <strong>Non-deliverable:</strong> {len(results) - deliverable}
</div>
<h2>Verification Results</h2>
<table>
  <thead>
    <tr>
      <th>Email</th><th>Format</th><th>MX</th><th>SMTP</th>
      <th>Disposable</th><th>Confidence</th><th>Risk</th>
    </tr>
  </thead>
  <tbody>{''.join(rows)}</tbody>
</table>
"""
        html = _HTML_TEMPLATE.format(
            title="Email Verification Report",
            generated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            body=body,
        )
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        return os.path.abspath(filepath)

    # ------------------------------------------------------------------
    # Header Analysis Reports
    # ------------------------------------------------------------------

    def report_header_analysis_json(self, analysis: Dict, filepath: str = None) -> str:
        """Export header analysis to JSON."""
        filepath = filepath or str(self.output_dir / f"header_analysis_{self._ts()}.json")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(analysis, f, indent=2, ensure_ascii=False, default=str)
        return os.path.abspath(filepath)

    def report_header_analysis_html(self, analysis: Dict, filepath: str = None) -> str:
        """
        Generate HTML report for header analysis.

        Args:
            analysis: Header analysis result dict
            filepath: Output path (auto-generated if None)

        Returns:
            Absolute path to HTML report
        """
        filepath = filepath or str(self.output_dir / f"header_analysis_{self._ts()}.html")
        Path(filepath).parent.mkdir(parents=True, exist_ok=True)

        meta = analysis.get('metadata', {})
        auth = analysis.get('authentication', {})
        sender = analysis.get('sender', {})
        security = analysis.get('security', {})
        routing = analysis.get('routing', [])
        attachments = analysis.get('attachments', [])

        def auth_badge(val):
            if val == 'pass':
                return '<span class="badge badge-green">pass</span>'
            elif val in ('fail', 'hardfail'):
                return '<span class="badge badge-red">fail</span>'
            elif val:
                return f'<span class="badge badge-yellow">{val}</span>'
            return '<span class="badge badge-grey">N/A</span>'

        routing_rows = ''.join(
            f"<tr><td>{i+1}</td><td>{self._esc(h.get('from_host',''))}</td>"
            f"<td>{self._esc(h.get('from_ip',''))}</td>"
            f"<td>{self._esc(h.get('by_server',''))}</td>"
            f"<td>{'✅' if h.get('tls') else '❌'}</td>"
            f"<td>{self._esc(h.get('date_iso',''))}</td></tr>"
            for i, h in enumerate(routing)
        )

        attach_rows = ''.join(
            f"<tr><td>{self._esc(a.get('filename',''))}</td>"
            f"<td>{self._esc(a.get('content_type',''))}</td>"
            f"<td>{a.get('size',0)} bytes</td></tr>"
            for a in attachments
        )

        risk_score = security.get('risk_score', 0)
        risk_level = security.get('risk_level', 'unknown')
        risk_badge = self._risk_badge(risk_level)

        body = f"""
<h2>Metadata</h2>
<table>
  <tr><th>Subject</th><td>{self._esc(meta.get('subject',''))}</td></tr>
  <tr><th>Date</th><td>{self._esc(meta.get('date_iso',''))}</td></tr>
  <tr><th>Message-ID</th><td>{self._esc(meta.get('message_id',''))}</td></tr>
  <tr><th>Content-Type</th><td>{self._esc(meta.get('content_type',''))}</td></tr>
  <tr><th>X-Mailer</th><td>{self._esc(meta.get('x_mailer',''))}</td></tr>
</table>

<h2>Sender</h2>
<table>
  <tr><th>From</th><td>{self._esc(sender.get('from',''))}</td></tr>
  <tr><th>Reply-To</th><td>{self._esc(sender.get('reply_to',''))}</td></tr>
  <tr><th>Return-Path</th><td>{self._esc(sender.get('return_path',''))}</td></tr>
  <tr><th>Domain Mismatch</th><td>{'<span class="badge badge-red">Yes</span>' if sender.get('domain_mismatch') else '<span class="badge badge-green">No</span>'}</td></tr>
</table>

<h2>Authentication</h2>
<table>
  <tr><th>SPF</th><td>{auth_badge(auth.get('spf'))}</td></tr>
  <tr><th>DKIM</th><td>{auth_badge(auth.get('dkim'))}</td></tr>
  <tr><th>DMARC</th><td>{auth_badge(auth.get('dmarc'))}</td></tr>
  <tr><th>DKIM Signature</th><td>{'<span class="badge badge-green">Present</span>' if auth.get('has_dkim_signature') else '<span class="badge badge-grey">None</span>'}</td></tr>
</table>

<h2>Security Analysis — Risk Score: {risk_score}/10 {risk_badge}</h2>
<table>
  <tr><th>Phishing Keywords</th><td>{', '.join(security.get('phishing_keywords', [])) or 'None'}</td></tr>
  <tr><th>URLs Found</th><td>{security.get('url_count', 0)}</td></tr>
  <tr><th>Suspicious URLs</th><td>{security.get('suspicious_url_count', 0)}</td></tr>
  <tr><th>Spoofing Risk</th><td>{'<span class="badge badge-red">Yes</span>' if security.get('spoofing_risk') else '<span class="badge badge-green">No</span>'}</td></tr>
  <tr><th>Reply-To Mismatch</th><td>{'<span class="badge badge-red">Yes</span>' if security.get('reply_to_mismatch') else '<span class="badge badge-green">No</span>'}</td></tr>
</table>

<h2>Routing ({len(routing)} hops)</h2>
<table>
  <thead><tr><th>#</th><th>From Host</th><th>From IP</th><th>By Server</th><th>TLS</th><th>Date</th></tr></thead>
  <tbody>{routing_rows or '<tr><td colspan="6">No routing info</td></tr>'}</tbody>
</table>

<h2>Attachments ({len(attachments)})</h2>
<table>
  <thead><tr><th>Filename</th><th>Content-Type</th><th>Size</th></tr></thead>
  <tbody>{attach_rows or '<tr><td colspan="3">No attachments</td></tr>'}</tbody>
</table>
"""
        html = _HTML_TEMPLATE.format(
            title="Email Header Analysis Report",
            generated_at=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            body=body,
        )
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        return os.path.abspath(filepath)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _ts(self) -> str:
        """Return a timestamp string for filenames."""
        return datetime.now().strftime('%Y%m%d_%H%M%S')

    def _esc(self, text) -> str:
        """HTML-escape a string."""
        return (
            str(text)
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;')
        )

    def _flatten(self, d: Dict, prefix: str = '') -> Dict:
        """Flatten a nested dict for CSV export."""
        flat = {}
        for key, value in d.items():
            full_key = f"{prefix}{key}" if prefix else key
            if isinstance(value, dict):
                flat.update(self._flatten(value, f"{full_key}_"))
            elif isinstance(value, list):
                flat[full_key] = str(value)
            else:
                flat[full_key] = value
        return flat

    def _confidence_badge(self, confidence: str) -> str:
        badges = {
            'high': '<span class="badge badge-green">High</span>',
            'medium': '<span class="badge badge-yellow">Medium</span>',
            'low': '<span class="badge badge-red">Low</span>',
            'invalid': '<span class="badge badge-red">Invalid</span>',
        }
        return badges.get(confidence, f'<span class="badge badge-grey">{confidence}</span>')

    def _risk_badge(self, risk: str) -> str:
        badges = {
            'low': '<span class="badge badge-green">Low</span>',
            'medium': '<span class="badge badge-yellow">Medium</span>',
            'high': '<span class="badge badge-red">High</span>',
            'critical': '<span class="badge badge-red">⚠ Critical</span>',
        }
        return badges.get(risk, f'<span class="badge badge-grey">{risk}</span>')

    def _smtp_badge(self, smtp_valid) -> str:
        if smtp_valid is True:
            return '<span class="badge badge-green">Pass</span>'
        elif smtp_valid is False:
            return '<span class="badge badge-red">Fail</span>'
        return '<span class="badge badge-grey">N/A</span>'
